-- Seed data for application types (105 total)
-- Organized by service categories

INSERT INTO application_types (service_id, name, slug, description, order_position, active) VALUES
-- Software Development (service_id = 1) - 25 types
(1, 'Web Applications', 'web-applications', 'Custom web applications built with modern frameworks', 1, 1),
(1, 'Mobile Applications', 'mobile-applications', 'Native and cross-platform mobile apps', 2, 1),
(1, 'Desktop Applications', 'desktop-applications', 'Windows, macOS, and Linux desktop software', 3, 1),
(1, 'E-commerce Platforms', 'e-commerce-platforms', 'Online stores and shopping platforms', 4, 1),
(1, 'Content Management Systems', 'content-management-systems', 'Custom CMS solutions', 5, 1),
(1, 'Learning Management Systems', 'learning-management-systems', 'Educational platforms and LMS', 6, 1),
(1, 'Healthcare Systems', 'healthcare-systems', 'Medical records and healthcare management', 7, 1),
(1, 'Financial Systems', 'financial-systems', 'Banking and financial software', 8, 1),
(1, 'Inventory Management', 'inventory-management', 'Stock and warehouse management systems', 9, 1),
(1, 'CRM Systems', 'crm-systems', 'Customer relationship management', 10, 1),
(1, 'ERP Systems', 'erp-systems', 'Enterprise resource planning', 11, 1),
(1, 'Booking Systems', 'booking-systems', 'Appointment and reservation platforms', 12, 1),
(1, 'Social Networks', 'social-networks', 'Community and social platforms', 13, 1),
(1, 'Marketplace Platforms', 'marketplace-platforms', 'Multi-vendor marketplaces', 14, 1),
(1, 'Real Estate Platforms', 'real-estate-platforms', 'Property listing and management', 15, 1),
(1, 'HR Management', 'hr-management', 'Human resources and payroll systems', 16, 1),
(1, 'Project Management', 'project-management', 'Task and project tracking tools', 17, 1),
(1, 'Analytics Dashboards', 'analytics-dashboards', 'Data visualization and reporting', 18, 1),
(1, 'Gaming Applications', 'gaming-applications', 'Browser and mobile games', 19, 1),
(1, 'IoT Applications', 'iot-applications', 'Internet of Things integrations', 20, 1),
(1, 'Blockchain Applications', 'blockchain-applications', 'DApps and smart contracts', 21, 1),
(1, 'API Development', 'api-development', 'RESTful and GraphQL APIs', 22, 1),
(1, 'Microservices', 'microservices', 'Distributed service architectures', 23, 1),
(1, 'Progressive Web Apps', 'progressive-web-apps', 'PWA development', 24, 1),
(1, 'Custom Integrations', 'custom-integrations', 'Third-party system integrations', 25, 1),

-- SaaS Platforms (service_id = 2) - 20 types
(2, 'Subscription Management', 'subscription-management', 'Recurring billing and subscriptions', 1, 1),
(2, 'Multi-tenant Architecture', 'multi-tenant-architecture', 'SaaS multi-tenancy solutions', 2, 1),
(2, 'User Authentication Services', 'user-authentication-services', 'Auth0, OAuth, SSO integrations', 3, 1),
(2, 'Cloud Storage Solutions', 'cloud-storage-solutions', 'File storage and sharing platforms', 4, 1),
(2, 'Collaboration Tools', 'collaboration-tools', 'Team collaboration software', 5, 1),
(2, 'Email Marketing Platforms', 'email-marketing-platforms', 'Campaign management and automation', 6, 1),
(2, 'Customer Support Systems', 'customer-support-systems', 'Helpdesk and ticketing', 7, 1),
(2, 'Video Conferencing', 'video-conferencing', 'Online meeting platforms', 8, 1),
(2, 'Document Management', 'document-management', 'Document storage and workflow', 9, 1),
(2, 'Workflow Automation', 'workflow-automation', 'Business process automation', 10, 1),
(2, 'Reporting Platforms', 'reporting-platforms', 'Business intelligence dashboards', 11, 1),
(2, 'Survey Platforms', 'survey-platforms', 'Online surveys and feedback', 12, 1),
(2, 'Event Management', 'event-management', 'Event planning and registration', 13, 1),
(2, 'Membership Platforms', 'membership-platforms', 'Member management portals', 14, 1),
(2, 'Online Course Platforms', 'online-course-platforms', 'E-learning SaaS solutions', 15, 1),
(2, 'Appointment Scheduling', 'appointment-scheduling', 'Calendar and booking SaaS', 16, 1),
(2, 'Invoice Management', 'invoice-management', 'Billing and invoicing platforms', 17, 1),
(2, 'Time Tracking', 'time-tracking', 'Employee time management', 18, 1),
(2, 'Performance Monitoring', 'performance-monitoring', 'Application performance SaaS', 19, 1),
(2, 'Security Monitoring', 'security-monitoring', 'Threat detection and monitoring', 20, 1),

-- Enterprise Solutions (service_id = 3) - 15 types
(3, 'Enterprise Portals', 'enterprise-portals', 'Corporate intranet portals', 1, 1),
(3, 'Document Workflow', 'document-workflow', 'Enterprise document workflows', 2, 1),
(3, 'Business Intelligence', 'business-intelligence', 'Enterprise BI solutions', 3, 1),
(3, 'Data Warehousing', 'data-warehousing', 'Enterprise data warehouses', 4, 1),
(3, 'Supply Chain Management', 'supply-chain-management', 'SCM enterprise systems', 5, 1),
(3, 'Manufacturing Execution', 'manufacturing-execution', 'MES systems', 6, 1),
(3, 'Quality Management', 'quality-management', 'QMS enterprise solutions', 7, 1),
(3, 'Compliance Management', 'compliance-management', 'Regulatory compliance systems', 8, 1),
(3, 'Risk Management', 'risk-management', 'Enterprise risk assessment', 9, 1),
(3, 'Asset Management', 'asset-management', 'Fixed asset tracking', 10, 1),
(3, 'Contract Management', 'contract-management', 'Contract lifecycle management', 11, 1),
(3, 'Procurement Systems', 'procurement-systems', 'Purchase and vendor management', 12, 1),
(3, 'Fleet Management', 'fleet-management', 'Vehicle fleet tracking', 13, 1),
(3, 'Facility Management', 'facility-management', 'Building and space management', 14, 1),
(3, 'Knowledge Management', 'knowledge-management', 'Enterprise knowledge bases', 15, 1),

-- AI & Automation (service_id = 4) - 20 types
(4, 'Chatbots', 'chatbots', 'AI-powered customer service bots', 1, 1),
(4, 'Virtual Assistants', 'virtual-assistants', 'Voice and text assistants', 2, 1),
(4, 'Natural Language Processing', 'natural-language-processing', 'NLP solutions', 3, 1),
(4, 'Computer Vision', 'computer-vision', 'Image recognition systems', 4, 1),
(4, 'Predictive Analytics', 'predictive-analytics', 'ML-based forecasting', 5, 1),
(4, 'Recommendation Engines', 'recommendation-engines', 'Personalization algorithms', 6, 1),
(4, 'Fraud Detection', 'fraud-detection', 'AI fraud prevention', 7, 1),
(4, 'Sentiment Analysis', 'sentiment-analysis', 'Opinion mining systems', 8, 1),
(4, 'Speech Recognition', 'speech-recognition', 'Voice-to-text solutions', 9, 1),
(4, 'Robotic Process Automation', 'robotic-process-automation', 'RPA implementations', 10, 1),
(4, 'Intelligent Document Processing', 'intelligent-document-processing', 'IDP solutions', 11, 1),
(4, 'Machine Learning Models', 'machine-learning-models', 'Custom ML model development', 12, 1),
(4, 'Deep Learning', 'deep-learning', 'Neural network solutions', 13, 1),
(4, 'Anomaly Detection', 'anomaly-detection', 'Outlier detection systems', 14, 1),
(4, 'Demand Forecasting', 'demand-forecasting', 'AI demand prediction', 15, 1),
(4, 'Price Optimization', 'price-optimization', 'Dynamic pricing engines', 16, 1),
(4, 'Customer Segmentation', 'customer-segmentation', 'AI clustering analysis', 17, 1),
(4, 'Churn Prediction', 'churn-prediction', 'Customer attrition models', 18, 1),
(4, 'Lead Scoring', 'lead-scoring', 'AI lead qualification', 19, 1),
(4, 'Content Generation', 'content-generation', 'AI content creation', 20, 1),

-- Modernization (service_id = 5) - 10 types
(5, 'Legacy System Migration', 'legacy-system-migration', 'Mainframe to cloud migration', 1, 1),
(5, 'Cloud Migration', 'cloud-migration', 'AWS, Azure, GCP migrations', 2, 1),
(5, 'Database Modernization', 'database-modernization', 'SQL to NoSQL migrations', 3, 1),
(5, 'Monolith to Microservices', 'monolith-to-microservices', 'Architecture refactoring', 4, 1),
(5, 'API Modernization', 'api-modernization', 'SOAP to REST conversions', 5, 1),
(5, 'UI/UX Modernization', 'ui-ux-modernization', 'Interface redesign', 6, 1),
(5, 'Infrastructure Modernization', 'infrastructure-modernization', 'DevOps transformations', 7, 1),
(5, 'Application Refactoring', 'application-refactoring', 'Code modernization', 8, 1),
(5, 'Technology Stack Upgrade', 'technology-stack-upgrade', 'Framework migrations', 9, 1),
(5, 'Digital Transformation', 'digital-transformation', 'End-to-end digitization', 10, 1),

-- UX Engineering (service_id = 6) - 10 types
(6, 'User Research', 'user-research', 'User interviews and studies', 1, 1),
(6, 'Wireframing', 'wireframing', 'Low-fidelity prototypes', 2, 1),
(6, 'Prototyping', 'prototyping', 'Interactive prototypes', 3, 1),
(6, 'Visual Design', 'visual-design', 'UI design systems', 4, 1),
(6, 'Design Systems', 'design-systems', 'Component libraries', 5, 1),
(6, 'Usability Testing', 'usability-testing', 'User testing sessions', 6, 1),
(6, 'Accessibility Audits', 'accessibility-audits', 'WCAG compliance', 7, 1),
(6, 'Information Architecture', 'information-architecture', 'Site structure design', 8, 1),
(6, 'Interaction Design', 'interaction-design', 'Motion and micro-interactions', 9, 1),
(6, 'UX Strategy', 'ux-strategy', 'Experience roadmaps', 10, 1);

-- Verify count
SELECT COUNT(*) as total_types FROM application_types;
